from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("integrated_scheduling","0009_finite_labor_068")]
    operations=[
        migrations.AddField(model_name="laborresource",name="hourly_cost",field=models.DecimalField(decimal_places=4,default=0,max_digits=12)),
        migrations.AddField(model_name="laborresource",name="preference_score",field=models.PositiveSmallIntegerField(default=50)),
        migrations.CreateModel(name="LaborRuleSet",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=40)),("name",models.CharField(max_length=120)),("effective_from",models.DateField()),("effective_to",models.DateField(blank=True,null=True)),("normal_daily_hours",models.DecimalField(decimal_places=2,default=8,max_digits=6)),("max_daily_hours",models.DecimalField(decimal_places=2,default=10,max_digits=6)),("max_weekly_hours",models.DecimalField(decimal_places=2,default=44,max_digits=6)),("minimum_rest_hours",models.DecimalField(decimal_places=2,default=11,max_digits=6)),("overtime_multiplier",models.DecimalField(decimal_places=3,default=1.5,max_digits=6)),("night_premium_percent",models.DecimalField(decimal_places=3,default=20,max_digits=6)),("night_start",models.TimeField(default="22:00")),("night_end",models.TimeField(default="05:00")),("overtime_allowed",models.BooleanField(default=True)),("is_active",models.BooleanField(default=True)),("plant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="labor_rule_sets",to="common.plant"))],options={"ordering":["plant__code","-effective_from"]}),
        migrations.AddField(model_name="schedulesolverrun",name="use_labor_costs",field=models.BooleanField(default=True)),
        migrations.AddField(model_name="schedulesolverrun",name="labor_cost_total",field=models.DecimalField(decimal_places=4,default=0,max_digits=18)),
        migrations.AddField(model_name="schedulesolverrun",name="labor_rule_set",field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="solver_runs",to="integrated_scheduling.laborruleset")),
        migrations.CreateModel(name="ScheduleSolverLaborCost",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("normal_minutes",models.PositiveIntegerField(default=0)),("overtime_minutes",models.PositiveIntegerField(default=0)),("night_minutes",models.PositiveIntegerField(default=0)),("base_cost",models.DecimalField(decimal_places=4,default=0,max_digits=16)),("overtime_premium",models.DecimalField(decimal_places=4,default=0,max_digits=16)),("night_premium",models.DecimalField(decimal_places=4,default=0,max_digits=16)),("total_cost",models.DecimalField(decimal_places=4,default=0,max_digits=16)),("details",models.JSONField(blank=True,default=dict)),("labor_assignment",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="cost_breakdown",to="integrated_scheduling.schedulesolverlaborassignment")),("rule_set",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="solver_costs",to="integrated_scheduling.laborruleset"))],options={"ordering":["labor_assignment__start","labor_assignment__labor_resource__employee_code"]}),
        migrations.AddConstraint(model_name="laborresource",constraint=models.CheckConstraint(condition=models.Q(("hourly_cost__gte",0)),name="ck_labor_hourly_cost_nonneg")),
        migrations.AddConstraint(model_name="laborresource",constraint=models.CheckConstraint(condition=models.Q(("preference_score__lte",100)),name="ck_labor_preference_lte100")),
        migrations.AddConstraint(model_name="laborruleset",constraint=models.UniqueConstraint(fields=("plant","code","effective_from"),name="uq_labor_ruleset_effective")),
        migrations.AddConstraint(model_name="laborruleset",constraint=models.CheckConstraint(condition=models.Q(("normal_daily_hours__gte",0)),name="ck_labor_rule_normal_nonneg")),
        migrations.AddConstraint(model_name="laborruleset",constraint=models.CheckConstraint(condition=models.Q(("max_daily_hours__gte",models.F("normal_daily_hours"))),name="ck_labor_rule_daily_ge_normal")),
        migrations.AddConstraint(model_name="laborruleset",constraint=models.CheckConstraint(condition=models.Q(("max_weekly_hours__gt",0)),name="ck_labor_rule_weekly_pos")),
        migrations.AddConstraint(model_name="laborruleset",constraint=models.CheckConstraint(condition=models.Q(("overtime_multiplier__gte",1)),name="ck_labor_rule_ot_ge1")),
        migrations.AddConstraint(model_name="laborruleset",constraint=models.CheckConstraint(condition=models.Q(("night_premium_percent__gte",0)),name="ck_labor_rule_night_nonneg")),
        migrations.AddConstraint(model_name="schedulesolverlaborcost",constraint=models.CheckConstraint(condition=models.Q(("base_cost__gte",0)),name="ck_labor_cost_base_nonneg")),
        migrations.AddConstraint(model_name="schedulesolverlaborcost",constraint=models.CheckConstraint(condition=models.Q(("total_cost__gte",0)),name="ck_labor_cost_total_nonneg")),
    ]
