from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("integrated_scheduling","0010_labor_cost_rules_069"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="ProductionSchedulePublication", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("version",models.PositiveIntegerField()),("status",models.CharField(choices=[("PUBLISHED","Publicada"),("SUPERSEDED","Substituída"),("CANCELLED","Cancelada")],default="PUBLISHED",max_length=16)),("frozen_until",models.DateTimeField(blank=True,null=True)),("published_at",models.DateTimeField(auto_now_add=True)),("notes",models.TextField(blank=True)),("metrics",models.JSONField(blank=True,default=dict)),
            ("plant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="schedule_publications",to="common.plant")),("scenario",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="publications",to="integrated_scheduling.integratedschedulescenario")),("solver_run",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="publications",to="integrated_scheduling.schedulesolverrun")),("published_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="production_schedule_publications",to=settings.AUTH_USER_MODEL))], options={"ordering":["-published_at","-version"]}),
        migrations.CreateModel(name="PublishedExecutionSlot", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("planned_start",models.DateTimeField()),("planned_end",models.DateTimeField()),("frozen",models.BooleanField(default=False)),("status",models.CharField(choices=[("PLANNED","Planejado"),("READY","Pronto"),("RUNNING","Executando"),("COMPLETED","Concluído"),("MISSED","Não executado")],default="PLANNED",max_length=16)),("actual_start",models.DateTimeField(blank=True,null=True)),("actual_end",models.DateTimeField(blank=True,null=True)),("team_snapshot",models.JSONField(blank=True,default=list)),("details",models.JSONField(blank=True,default=dict)),
            ("publication",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="slots",to="integrated_scheduling.productionschedulepublication")),("operation",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="official_schedule_slots",to="production.workorderoperation")),("work_center",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="official_schedule_slots",to="masterdata.workcenter")),("machine",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="official_schedule_slots",to="shopfloor.machine")),("source_assignment",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="published_execution_slots",to="integrated_scheduling.schedulesolverassignment"))], options={"ordering":["planned_start","work_center__code"]}),
        migrations.CreateModel(name="ScheduleExecutionDeviation", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("deviation_type",models.CharField(choices=[("LATE_START","Início atrasado"),("LATE_FINISH","Fim atrasado"),("MACHINE_BREAKDOWN","Quebra de máquina"),("MATERIAL_SHORTAGE","Falta de material"),("LABOR_ABSENCE","Ausência de operador"),("MANUAL","Ocorrência manual")],max_length=24)),("detected_at",models.DateTimeField()),("deviation_minutes",models.IntegerField(default=0)),("details",models.JSONField(blank=True,default=dict)),("resolved_at",models.DateTimeField(blank=True,null=True)),("slot",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="deviations",to="integrated_scheduling.publishedexecutionslot"))], options={"ordering":["-detected_at"]}),
        migrations.CreateModel(name="ReschedulingTrigger", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("trigger_type",models.CharField(choices=[("MACHINE_BREAKDOWN","Quebra de máquina"),("MATERIAL_SHORTAGE","Falta de material"),("LABOR_ABSENCE","Ausência de operador"),("PRIORITY_CHANGE","Mudança de prioridade"),("MANUAL","Manual")],max_length=24)),("source_type",models.CharField(blank=True,max_length=60)),("source_id",models.CharField(blank=True,max_length=80)),("affected_from",models.DateTimeField()),("idempotency_key",models.CharField(max_length=160,unique=True)),("status",models.CharField(choices=[("NEW","Novo"),("PROCESSING","Processando"),("RESCHEDULED","Reprogramado"),("IGNORED","Ignorado"),("FAILED","Falhou")],default="NEW",max_length=16)),("auto_reschedule",models.BooleanField(default=True)),("payload",models.JSONField(blank=True,default=dict)),("processed_at",models.DateTimeField(blank=True,null=True)),("error_message",models.TextField(blank=True)),
            ("plant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="rescheduling_triggers",to="common.plant")),("publication",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="rescheduling_triggers",to="integrated_scheduling.productionschedulepublication")),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="rescheduling_triggers",to=settings.AUTH_USER_MODEL)),("resulting_scenario",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="rescheduling_triggers",to="integrated_scheduling.integratedschedulescenario")),("resulting_solver_run",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="rescheduling_triggers",to="integrated_scheduling.schedulesolverrun"))], options={"ordering":["-created_at"]}),
        migrations.AddConstraint(model_name="productionschedulepublication",constraint=models.UniqueConstraint(fields=("plant","version"),name="uq_schedule_publication_version")),
        migrations.AddConstraint(model_name="publishedexecutionslot",constraint=models.UniqueConstraint(fields=("publication","operation"),name="uq_pubslot_publication_operation")),
        migrations.AddConstraint(model_name="publishedexecutionslot",constraint=models.CheckConstraint(condition=models.Q(("planned_end__gt",models.F("planned_start"))),name="ck_pubslot_window")),
        migrations.AddIndex(model_name="productionschedulepublication",index=models.Index(fields=["plant","status","published_at"],name="ix_schedpub_plant_status")),
        migrations.AddIndex(model_name="publishedexecutionslot",index=models.Index(fields=["publication","planned_start"],name="ix_pubslot_pub_start")),
        migrations.AddIndex(model_name="publishedexecutionslot",index=models.Index(fields=["machine","planned_start"],name="ix_pubslot_machine_start")),
        migrations.AddIndex(model_name="scheduleexecutiondeviation",index=models.Index(fields=["slot","deviation_type","detected_at"],name="ix_execdev_slot_type")),
        migrations.AddIndex(model_name="reschedulingtrigger",index=models.Index(fields=["plant","status","affected_from"],name="ix_replantrigger_status")),
    ]
