from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone

class Migration(migrations.Migration):
    dependencies=[('integrated_scheduling','0016_customer_confirmation_075'),('demand','0003_sales_delivery_076')]
    operations=[
      migrations.CreateModel(name='OTIFLineResult',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('reference',models.CharField(choices=[('REQUESTED','Solicitada'),('APPROVED_PROMISE','Promessa aprovada'),('CUSTOMER_ACCEPTED','Aceita pelo cliente')],default='CUSTOMER_ACCEPTED',max_length=24)),('requested_date',models.DateField()),('approved_promise_date',models.DateField(blank=True,null=True)),('accepted_date',models.DateField(blank=True,null=True)),('reference_date',models.DateField()),('ordered_quantity',models.DecimalField(decimal_places=4,max_digits=18)),('delivered_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=18)),('first_delivery_date',models.DateField(blank=True,null=True)),('full_delivery_date',models.DateField(blank=True,null=True)),('on_time',models.BooleanField(default=False)),('in_full',models.BooleanField(default=False)),('otif',models.BooleanField(default=False)),('days_late',models.IntegerField(default=0)),('primary_cause',models.CharField(blank=True,max_length=32)),('cause_details',models.JSONField(blank=True,default=dict)),('evaluated_at',models.DateTimeField(default=timezone.now)),('sales_order_line',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='otif_results',to='demand.salesorderline'))],options={'ordering':['-evaluated_at']}),
      migrations.CreateModel(name='ServiceLevelCause',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('category',models.CharField(choices=[('MATERIAL','Material'),('CAPACITY','Capacidade'),('MACHINE','Máquina'),('LABOR','Mão de obra'),('QUALITY','Qualidade'),('LOGISTICS','Logística'),('COMMERCIAL','Comercial'),('CUSTOMER','Cliente'),('UNKNOWN','Não identificada')],default='UNKNOWN',max_length=20)),('code',models.CharField(blank=True,max_length=50)),('description',models.CharField(max_length=240)),('source_type',models.CharField(blank=True,max_length=60)),('source_id',models.CharField(blank=True,max_length=80)),('minutes_impact',models.PositiveIntegerField(default=0)),('is_primary',models.BooleanField(default=False)),('details',models.JSONField(blank=True,default=dict)),('otif_result',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='causes',to='integrated_scheduling.otiflineresult'))],options={'ordering':['-is_primary','category','created_at']}),
      migrations.AddConstraint(model_name='otiflineresult',constraint=models.UniqueConstraint(fields=('sales_order_line','reference'),name='uq_otif_line_reference')),
      migrations.AddIndex(model_name='otiflineresult',index=models.Index(fields=['reference','otif','reference_date'],name='ix_otif_ref_flag_date')),
      migrations.AddIndex(model_name='otiflineresult',index=models.Index(fields=['sales_order_line','evaluated_at'],name='ix_otif_line_eval')),
      migrations.AddIndex(model_name='servicelevelcause',index=models.Index(fields=['category','is_primary'],name='ix_slcause_category_primary')),
    ]
