from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
class Migration(migrations.Migration):
    dependencies=[('integrated_scheduling','0018_service_level_management_077'),('demand','0004_sales_line_price_078')]
    operations=[
      migrations.CreateModel(name='ForecastAccuracySnapshot',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('period_start',models.DateField()),('period_end',models.DateField()),('forecast_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('actual_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('absolute_error_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('wape_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('forecast_accuracy_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('bias_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('item_count',models.PositiveIntegerField(default=0)),('details',models.JSONField(blank=True,default=dict)),('calculated_at',models.DateTimeField(default=django.utils.timezone.now)),('plant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='forecast_accuracy_snapshots',to='common.plant'))],options={'ordering':['-period_start','plant__code'] }),
      migrations.CreateModel(name='ExecutiveSAndOPSnapshot',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('period_start',models.DateField()),('period_end',models.DateField()),('otif_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('fill_rate_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('forecast_accuracy_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('forecast_bias_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('overdue_backlog_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('backlog_value',models.DecimalField(decimal_places=2,default=0,max_digits=22)),('revenue_at_risk',models.DecimalField(decimal_places=2,default=0,max_digits=22)),('revenue_coverage_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('inventory_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('inventory_value',models.DecimalField(decimal_places=2,default=0,max_digits=22)),('oee_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('capacity_utilization_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('open_demand_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('approved_forecast_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('planned_supply_quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('details',models.JSONField(blank=True,default=dict)),('calculated_at',models.DateTimeField(default=django.utils.timezone.now)),('plant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='executive_sop_snapshots',to='common.plant'))],options={'ordering':['-period_start','plant__code']}),
      migrations.CreateModel(name='SAndOPScenario',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=160)),('horizon_start',models.DateField()),('horizon_end',models.DateField()),('status',models.CharField(choices=[('DRAFT','Rascunho'),('SIMULATED','Simulado'),('APPROVED','Aprovado'),('ARCHIVED','Arquivado')],default='DRAFT',max_length=16)),('demand_change_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('capacity_change_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('inventory_change_pct',models.DecimalField(decimal_places=2,default=0,max_digits=8)),('baseline',models.JSONField(blank=True,default=dict)),('simulated',models.JSONField(blank=True,default=dict)),('assumptions',models.JSONField(blank=True,default=dict)),('approved_at',models.DateTimeField(blank=True,null=True)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='approved_sop_scenarios',to='auth.user')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='created_sop_scenarios',to='auth.user')),('plant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sop_scenarios',to='common.plant'))],options={'ordering':['-created_at']}) ,
      migrations.AddConstraint(model_name='forecastaccuracysnapshot',constraint=models.UniqueConstraint(fields=('plant','period_start','period_end'),name='uq_fcacc_plant_period')),
      migrations.AddConstraint(model_name='executivesandopsnapshot',constraint=models.UniqueConstraint(fields=('plant','period_start','period_end'),name='uq_execsop_plant_period')),
      migrations.AddConstraint(model_name='sandopscenario',constraint=models.CheckConstraint(condition=models.Q(('horizon_end__gte',models.F('horizon_start'))),name='ck_sop_scenario_dates')),
      migrations.AddIndex(model_name='forecastaccuracysnapshot',index=models.Index(fields=['plant','period_start'],name='ix_fcacc_plant_period')),
      migrations.AddIndex(model_name='executivesandopsnapshot',index=models.Index(fields=['plant','period_start'],name='ix_execsop_plant_period')),
      migrations.AddIndex(model_name='sandopscenario',index=models.Index(fields=['plant','status','horizon_start'],name='ix_sop_plant_status')),
    ]
