from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("integrated_scheduling","0025_mps_financial_whatif_084"),("masterdata","0002_supplier_payment_terms_085"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="MPSFinancialBudget",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=60)),("name",models.CharField(max_length=160)),("period_start",models.DateField()),("period_end",models.DateField()),("bucket_type",models.CharField(choices=[("WEEKLY","Semanal"),("MONTHLY","Mensal")],default="MONTHLY",max_length=10)),("status",models.CharField(choices=[("DRAFT","Rascunho"),("APPROVED","Aprovado"),("ARCHIVED","Arquivado")],default="DRAFT",max_length=12)),("notes",models.TextField(blank=True)),("approved_at",models.DateTimeField(blank=True,null=True)),("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="mps_financial_budgets_approved",to=settings.AUTH_USER_MODEL)),("plant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="mps_financial_budgets",to="common.plant"))],options={"ordering":["-period_start","code"]}),
        migrations.CreateModel(name="MPSFinancialBudgetLine",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("bucket_date",models.DateField()),("category",models.CharField(choices=[("PURCHASE_CASH","Desembolso de compras"),("LABOR","Mão de obra"),("MACHINE","Máquina"),("OVERHEAD","Overhead/setup"),("TOTAL_CASH","Caixa operacional total"),("INVENTORY_VALUE","Estoque em valor")],max_length=24)),("amount",models.DecimalField(decimal_places=2,default=0,max_digits=24)),("notes",models.CharField(blank=True,max_length=240)),("budget",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="lines",to="integrated_scheduling.mpsfinancialbudget"))],options={"ordering":["bucket_date","category"]}),
        migrations.CreateModel(name="MPSRevisionSimulationCashFlowBucket",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("bucket_date",models.DateField()),("category",models.CharField(choices=[("PURCHASE_CASH","Desembolso de compras"),("LABOR","Mão de obra"),("MACHINE","Máquina"),("OVERHEAD","Overhead/setup"),("TOTAL_CASH","Caixa operacional total"),("INVENTORY_VALUE","Estoque em valor")],max_length=24)),("left_value",models.DecimalField(decimal_places=2,default=0,max_digits=24)),("right_value",models.DecimalField(decimal_places=2,default=0,max_digits=24)),("delta_value",models.DecimalField(decimal_places=2,default=0,max_digits=24)),("budget_value",models.DecimalField(blank=True,decimal_places=2,max_digits=24,null=True)),("variance_to_budget",models.DecimalField(blank=True,decimal_places=2,max_digits=24,null=True)),("details",models.JSONField(blank=True,default=dict)),("budget",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="simulation_buckets",to="integrated_scheduling.mpsfinancialbudget")),("simulation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="cashflow_buckets",to="integrated_scheduling.mpsrevisionsimulation"))],options={"ordering":["bucket_date","category"]}),
        migrations.AddConstraint(model_name="mpsfinancialbudget",constraint=models.UniqueConstraint(fields=("plant","code"),name="uq_mpsfinbudget_plant_code")),
        migrations.AddConstraint(model_name="mpsfinancialbudget",constraint=models.CheckConstraint(condition=models.Q(("period_end__gte",models.F("period_start"))),name="ck_mpsfinbudget_period")),
        migrations.AddConstraint(model_name="mpsfinancialbudgetline",constraint=models.UniqueConstraint(fields=("budget","bucket_date","category"),name="uq_mpsfinbudget_line")),
        migrations.AddIndex(model_name="mpsfinancialbudgetline",index=models.Index(fields=["budget","bucket_date"],name="ix_mpsfinbudget_bucket")),
        migrations.AddConstraint(model_name="mpsrevisionsimulationcashflowbucket",constraint=models.UniqueConstraint(fields=("simulation","bucket_date","category"),name="uq_mpssimcash_bucket")),
        migrations.AddIndex(model_name="mpsrevisionsimulationcashflowbucket",index=models.Index(fields=["simulation","bucket_date"],name="ix_mpssimcash_bucket")),
    ]
