from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('integrated_scheduling','0028_financing_capacity_087'),
        ('masterdata','0003_supplier_installments_086'),
        ('common','0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AddField(model_name='mpsrevisionsimulation',name='planning_overrides',field=models.JSONField(blank=True,default=dict)),
        migrations.CreateModel(name='MPSOptimizationPolicy',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),
            ('max_candidates',models.PositiveIntegerField(default=5)),('move_fraction_percent',models.DecimalField(decimal_places=3,default=20,max_digits=7)),('max_week_shift',models.PositiveIntegerField(default=1)),('allow_supplier_switch',models.BooleanField(default=True)),('require_optimizer_before_approval',models.BooleanField(default=False)),('supplier_price_tolerance_percent',models.DecimalField(decimal_places=3,default=10,max_digits=7)),
            ('weight_shortage',models.DecimalField(decimal_places=4,default=100,max_digits=10)),('weight_rccp_overload',models.DecimalField(decimal_places=4,default=10,max_digits=10)),('weight_uncovered_financing',models.DecimalField(decimal_places=4,default=1,max_digits=10)),('weight_interest',models.DecimalField(decimal_places=4,default=1,max_digits=10)),('weight_inventory',models.DecimalField(decimal_places=4,default=.10,max_digits=10)),('weight_purchase_spend',models.DecimalField(decimal_places=4,default=.10,max_digits=10)),('notes',models.TextField(blank=True)),
            ('plant',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='mps_optimization_policy',to='common.plant'))]),
        migrations.AddConstraint(model_name='mpsoptimizationpolicy',constraint=models.CheckConstraint(condition=models.Q(max_candidates__gt=0),name='ck_mpsopt_candidates_gt0')),
        migrations.AddConstraint(model_name='mpsoptimizationpolicy',constraint=models.CheckConstraint(condition=models.Q(move_fraction_percent__gt=0),name='ck_mpsopt_move_gt0')),
        migrations.AddConstraint(model_name='mpsoptimizationpolicy',constraint=models.CheckConstraint(condition=models.Q(move_fraction_percent__lte=100),name='ck_mpsopt_move_lte100')),
        migrations.CreateModel(name='MPSRevisionOptimizationRun',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('status',models.CharField(choices=[('DRAFT','Rascunho'),('RUNNING','Executando'),('COMPLETED','Concluído'),('FAILED','Falhou')],default='DRAFT',max_length=12)),('summary',models.JSONField(blank=True,default=dict)),('started_at',models.DateTimeField(blank=True,null=True)),('completed_at',models.DateTimeField(blank=True,null=True)),('error_message',models.TextField(blank=True)),
            ('compare_revision',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='optimization_baselines',to='integrated_scheduling.mpsrevision')),('revision',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='optimization_runs',to='integrated_scheduling.mpsrevision')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_optimization_runs_created',to=settings.AUTH_USER_MODEL))],options={'ordering':['-created_at']}),
        migrations.AddIndex(model_name='mpsrevisionoptimizationrun',index=models.Index(fields=['revision','status'],name='ix_mpsopt_run_status')),
        migrations.CreateModel(name='MPSRevisionOptimizationCandidate',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('strategy',models.CharField(choices=[('BASELINE','Revisão atual'),('SHIFT_LATER','Postergar volume'),('SHIFT_EARLIER','Antecipar volume'),('LEVEL_LOAD','Nivelar buckets'),('SUPPLIER_TERMS','Fornecedor/prazo financeiro')],max_length=24)),('name',models.CharField(max_length=160)),('planning_overrides',models.JSONField(blank=True,default=dict)),('metrics',models.JSONField(blank=True,default=dict)),('score',models.DecimalField(blank=True,decimal_places=6,max_digits=24,null=True)),('rank',models.PositiveIntegerField(blank=True,null=True)),('is_recommended',models.BooleanField(default=False)),('notes',models.TextField(blank=True)),
            ('generated_revision',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='optimization_candidates',to='integrated_scheduling.mpsrevision')),('optimization_run',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='candidates',to='integrated_scheduling.mpsrevisionoptimizationrun')),('simulation',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='optimization_candidates',to='integrated_scheduling.mpsrevisionsimulation'))],options={'ordering':['rank','score','id']}),
        migrations.AddIndex(model_name='mpsrevisionoptimizationcandidate',index=models.Index(fields=['optimization_run','rank'],name='ix_mpsopt_candidate_rank')),
        migrations.CreateModel(name='MPSRevisionOptimizationAction',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('action_type',models.CharField(max_length=30)),('source_date',models.DateField(blank=True,null=True)),('target_date',models.DateField(blank=True,null=True)),('quantity',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('details',models.JSONField(blank=True,default=dict)),
            ('candidate',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='actions',to='integrated_scheduling.mpsrevisionoptimizationcandidate')),('item',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='mps_optimization_actions',to='masterdata.item')),('supplier_from',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='optimization_actions_from',to='masterdata.supplier')),('supplier_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='optimization_actions_to',to='masterdata.supplier'))],options={'ordering':['candidate','id']}),
    ]
