from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('integrated_scheduling','0031_mps_decision_cockpit_090'),('common','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='MPSDecisionGovernancePolicy',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('required_areas',models.JSONField(blank=True,default=list)),('require_area_approvals',models.BooleanField(default=True)),('require_risk_acceptance',models.BooleanField(default=True)),('require_conditions_closed',models.BooleanField(default=False)),('minimum_participants',models.PositiveIntegerField(default=2)),('is_active',models.BooleanField(default=True)),('plant',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='mps_decision_governance_policy',to='common.plant'))]),
        migrations.CreateModel(name='MPSDecisionMeeting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(default='Reunião de decisão MRP/MPS',max_length=180)),('meeting_at',models.DateTimeField(blank=True,null=True)),('location',models.CharField(blank=True,max_length=180)),('agenda',models.TextField(blank=True)),('minutes',models.TextField(blank=True)),('conclusion',models.TextField(blank=True)),('minute_number',models.CharField(blank=True,max_length=60)),('closed_at',models.DateTimeField(blank=True,null=True)),('closed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_meetings_closed',to=settings.AUTH_USER_MODEL)),('cockpit',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='meeting',to='integrated_scheduling.mpsdecisioncockpit'))]),
        migrations.CreateModel(name='MPSDecisionParticipant',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=160)),('area',models.CharField(choices=[('PLANNING','Planejamento'),('PRODUCTION','Produção'),('PURCHASING','Compras'),('SALES','Comercial'),('FINANCE','Finanças'),('QUALITY','Qualidade'),('MAINTENANCE','Manutenção'),('EXECUTIVE','Executivo'),('OTHER','Outra')],max_length=20)),('role_title',models.CharField(blank=True,max_length=120)),('attended',models.BooleanField(default=True)),('is_decision_maker',models.BooleanField(default=False)),('meeting',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='participants',to='integrated_scheduling.mpsdecisionmeeting')),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_participations',to=settings.AUTH_USER_MODEL))],options={'ordering':['area','name']}),
        migrations.AddIndex(model_name='mpsdecisionparticipant',index=models.Index(fields=['meeting','area'],name='ix_mpsdec_part_area')),
        migrations.CreateModel(name='MPSDecisionComment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('area',models.CharField(choices=[('PLANNING','Planejamento'),('PRODUCTION','Produção'),('PURCHASING','Compras'),('SALES','Comercial'),('FINANCE','Finanças'),('QUALITY','Qualidade'),('MAINTENANCE','Manutenção'),('EXECUTIVE','Executivo'),('OTHER','Outra')],default='OTHER',max_length=20)),('text',models.TextField()),('is_resolved',models.BooleanField(default=False)),('resolved_at',models.DateTimeField(blank=True,null=True)),('author',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_formal_comments',to=settings.AUTH_USER_MODEL)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='formal_comments',to='integrated_scheduling.mpsdecisioncockpit'))],options={'ordering':['created_at']}),
        migrations.CreateModel(name='MPSDecisionRiskAcceptance',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('category',models.CharField(max_length=40)),('description',models.TextField()),('impact',models.TextField(blank=True)),('mitigation',models.TextField(blank=True)),('status',models.CharField(choices=[('OPEN','Aberto'),('ACCEPTED','Risco aceito'),('MITIGATED','Mitigado'),('REJECTED','Não aceito')],default='OPEN',max_length=16)),('accepted_at',models.DateTimeField(blank=True,null=True)),('accepted_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_risks_accepted',to=settings.AUTH_USER_MODEL)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='risk_acceptances',to='integrated_scheduling.mpsdecisioncockpit')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_risks_owned',to=settings.AUTH_USER_MODEL))],options={'ordering':['status','category','id']}),
        migrations.CreateModel(name='MPSDecisionCondition',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('description',models.TextField()),('due_date',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('OPEN','Aberta'),('SATISFIED','Atendida'),('WAIVED','Dispensada')],default='OPEN',max_length=16)),('closed_at',models.DateTimeField(blank=True,null=True)),('closed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_conditions_closed',to=settings.AUTH_USER_MODEL)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='approval_conditions',to='integrated_scheduling.mpsdecisioncockpit')),('owner',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_conditions_owned',to=settings.AUTH_USER_MODEL))],options={'ordering':['status','due_date','id']}),
        migrations.CreateModel(name='MPSDecisionAreaApproval',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('area',models.CharField(choices=[('PLANNING','Planejamento'),('PRODUCTION','Produção'),('PURCHASING','Compras'),('SALES','Comercial'),('FINANCE','Finanças'),('QUALITY','Qualidade'),('MAINTENANCE','Manutenção'),('EXECUTIVE','Executivo'),('OTHER','Outra')],max_length=20)),('is_required',models.BooleanField(default=True)),('decision',models.CharField(choices=[('PENDING','Pendente'),('APPROVED','Aprovado'),('REJECTED','Rejeitado'),('ABSTAINED','Abstenção')],default='PENDING',max_length=16)),('decided_at',models.DateTimeField(blank=True,null=True)),('comment',models.TextField(blank=True)),('approver',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_area_approvals',to=settings.AUTH_USER_MODEL)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='area_approvals',to='integrated_scheduling.mpsdecisioncockpit'))],options={'ordering':['area']}),
        migrations.AddConstraint(model_name='mpsdecisionareaapproval',constraint=models.UniqueConstraint(fields=('cockpit','area'),name='uq_mpsdec_cockpit_area')),
        migrations.AddIndex(model_name='mpsdecisionareaapproval',index=models.Index(fields=['cockpit','decision'],name='ix_mpsdec_area_decision')),
        migrations.CreateModel(name='MPSDecisionAttachment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('file',models.FileField(upload_to='mps_decisions/%Y/%m/')),('title',models.CharField(blank=True,max_length=180)),('description',models.TextField(blank=True)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='attachments_091',to='integrated_scheduling.mpsdecisioncockpit')),('uploaded_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_attachments',to=settings.AUTH_USER_MODEL))],options={'ordering':['created_at']}),
    ]
