from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies=[('integrated_scheduling','0032_mps_decision_minutes_091'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='MPSDecisionApprovalMatrix',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('level',models.CharField(choices=[('MANAGER','Gerente'),('DIRECTOR','Diretor'),('EXECUTIVE_COMMITTEE','Comitê executivo')],max_length=24)),('priority',models.PositiveIntegerField(default=10)),('is_default',models.BooleanField(default=False)),('min_purchase_spend',models.DecimalField(decimal_places=2,default=0,max_digits=22)),('min_peak_working_capital',models.DecimalField(decimal_places=2,default=0,max_digits=22)),('min_peak_financing_need',models.DecimalField(decimal_places=2,default=0,max_digits=22)),('min_service_risk_proxy',models.DecimalField(decimal_places=4,default=0,max_digits=22)),('required_groups',models.JSONField(blank=True,default=list)),('required_signatures',models.PositiveIntegerField(default=1)),('is_active',models.BooleanField(default=True)),('plant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='mps_decision_approval_matrix',to='common.plant'))],options={'ordering':['plant','priority','id']}),
      migrations.CreateModel(name='MPSDecisionApprovalRequirement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('level',models.CharField(choices=[('MANAGER','Gerente'),('DIRECTOR','Diretor'),('EXECUTIVE_COMMITTEE','Comitê executivo')],max_length=24)),('required_groups',models.JSONField(blank=True,default=list)),('required_signatures',models.PositiveIntegerField(default=1)),('exposure_snapshot',models.JSONField(blank=True,default=dict)),('decision_content_hash',models.CharField(max_length=64)),('status',models.CharField(choices=[('PENDING','Pendente'),('SATISFIED','Atendida'),('SUPERSEDED','Substituída')],default='PENDING',max_length=16)),('satisfied_at',models.DateTimeField(blank=True,null=True)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='authority_requirements',to='integrated_scheduling.mpsdecisioncockpit')),('matrix_rule',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='requirements',to='integrated_scheduling.mpsdecisionapprovalmatrix'))],options={'ordering':['cockpit','-created_at']}),
      migrations.CreateModel(name='MPSDecisionElectronicSignature',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('authentication_method',models.CharField(choices=[('PASSWORD','Senha revalidada'),('SESSION','Sessão autenticada/SSO')],max_length=16)),('confirmation_statement',models.CharField(max_length=180)),('signed_at',models.DateTimeField()),('content_hash',models.CharField(max_length=64)),('signature_hash',models.CharField(max_length=64)),('signature_version',models.CharField(default='APP-HMAC-SHA256-V1',max_length=40)),('signer_username',models.CharField(max_length=150)),('signer_groups',models.JSONField(blank=True,default=list)),('client_ip',models.GenericIPAddressField(blank=True,null=True)),('user_agent',models.CharField(blank=True,max_length=300)),('requirement',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='signatures',to='integrated_scheduling.mpsdecisionapprovalrequirement')),('signer',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='mps_decision_electronic_signatures',to=settings.AUTH_USER_MODEL))],options={'ordering':['signed_at','id']}),
      migrations.AddConstraint(model_name='mpsdecisionelectronicsignature',constraint=models.UniqueConstraint(fields=('requirement','signer'),name='uq_mpsdec_req_signer')),
      migrations.AddIndex(model_name='mpsdecisionapprovalmatrix',index=models.Index(fields=['plant','is_active','priority'],name='ix_mpsdec_matrix_active')),
      migrations.AddIndex(model_name='mpsdecisionapprovalrequirement',index=models.Index(fields=['cockpit','status'],name='ix_mpsdec_authreq_status')),
      migrations.AddIndex(model_name='mpsdecisionelectronicsignature',index=models.Index(fields=['requirement','signed_at'],name='ix_mpsdec_sig_req_time')),
    ]
