from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies=[('integrated_scheduling','0033_mps_decision_authority_092'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='MPSDecisionAuditEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('sequence',models.PositiveIntegerField()),('event_type',models.CharField(choices=[('COCKPIT_CREATED','Cockpit criado'),('CANDIDATE_SELECTED','Cenário selecionado'),('SIMULATION_REFERENCED','Simulação referenciada'),('LEGACY_BOOTSTRAP','Bootstrap legado'),('SUBMITTED','Enviado para aprovação'),('AREA_DECISION','Decisão de área'),('RISK_ACCEPTED','Risco aceito'),('AUTHORITY_CREATED','Alçada criada'),('ELECTRONIC_SIGNATURE','Assinatura eletrônica'),('EXECUTIVE_APPROVED','Aprovação executiva'),('EXECUTIVE_REJECTED','Rejeição executiva'),('OFFICIAL_FROZEN','Plano oficial congelado'),('EVIDENCE_EXPORTED','Pacote de evidências exportado'),('NOTE','Evento informativo')],max_length=40)),('occurred_at',models.DateTimeField(default=django.utils.timezone.now)),('actor_username',models.CharField(blank=True,max_length=150)),('payload',models.JSONField(blank=True,default=dict)),('previous_hash',models.CharField(blank=True,max_length=64)),('event_hash',models.CharField(max_length=64,unique=True)),('hash_algorithm',models.CharField(default='SHA256',max_length=24)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_audit_events',to=settings.AUTH_USER_MODEL)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='audit_events',to='integrated_scheduling.mpsdecisioncockpit'))],options={'ordering':['cockpit','sequence']}),
      migrations.CreateModel(name='MPSDecisionEvidenceExport',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('generated_at',models.DateTimeField(default=django.utils.timezone.now)),('audit_head_hash',models.CharField(blank=True,max_length=64)),('audit_event_count',models.PositiveIntegerField(default=0)),('verification_ok',models.BooleanField(default=False)),('manifest',models.JSONField(blank=True,default=dict)),('package_sha256',models.CharField(blank=True,max_length=64)),('file_name',models.CharField(blank=True,max_length=220)),('cockpit',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='evidence_exports',to='integrated_scheduling.mpsdecisioncockpit')),('generated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='mps_decision_evidence_exports',to=settings.AUTH_USER_MODEL))],options={'ordering':['-generated_at','-id']}),
      migrations.AddConstraint(model_name='mpsdecisionauditevent',constraint=models.UniqueConstraint(fields=('cockpit','sequence'),name='uq_mpsdec_audit_seq')),
      migrations.AddIndex(model_name='mpsdecisionauditevent',index=models.Index(fields=['cockpit','sequence'],name='ix_mpsdec_audit_seq')),
      migrations.AddIndex(model_name='mpsdecisionauditevent',index=models.Index(fields=['event_type','occurred_at'],name='ix_mpsdec_audit_type')),
      migrations.AddIndex(model_name='mpsdecisionevidenceexport',index=models.Index(fields=['cockpit','generated_at'],name='ix_mpsdec_export_time')),
    ]
