from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies=[('integrated_scheduling','0038_mps_compliance_escalation_097'),('common','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.AddField(model_name='mpsdecisioncomplianceincident',name='responsible_area',field=models.CharField(blank=True,max_length=40)),
        migrations.AddField(model_name='mpsdecisioncomplianceincident',name='responsible_user',field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='responsible_mps_compliance_incidents',to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='mpscomplianceescalationrule',name='clock_basis',field=models.CharField(choices=[('FIRST_SEEN','Desde abertura'),('ACKNOWLEDGED','Desde reconhecimento')],default='FIRST_SEEN',max_length=20)),
        migrations.AddField(model_name='mpscomplianceescalationrule',name='notification_channels',field=models.JSONField(blank=True,default=list,help_text='EMAIL/API/TEAMS/SLACK; vazio usa EMAIL.')),
        migrations.AddField(model_name='mpscomplianceescalationrule',name='channel_endpoints',field=models.JSONField(blank=True,default=dict,help_text='Endpoints por canal.')),
        migrations.AddField(model_name='mpscomplianceoncallcontact',name='include_holidays',field=models.BooleanField(default=False,help_text='Atende também em feriados corporativos.')),
        migrations.AddField(model_name='mpscomplianceoncallcontact',name='channels',field=models.JSONField(blank=True,default=list,help_text='EMAIL/API/TEAMS/SLACK; vazio = EMAIL.')),
        migrations.AddField(model_name='mpscomplianceoncallcontact',name='api_url',field=models.URLField(blank=True)),
        migrations.AddField(model_name='mpscomplianceoncallcontact',name='teams_webhook_url',field=models.URLField(blank=True)),
        migrations.AddField(model_name='mpscomplianceoncallcontact',name='slack_webhook_url',field=models.URLField(blank=True)),
        migrations.CreateModel(name='MPSComplianceHoliday',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('date',models.DateField()),('name',models.CharField(max_length=120)),('is_active',models.BooleanField(default=True)),('plant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='mps_compliance_holidays',to='common.plant'))],options={'ordering':['plant__code','date']}),
        migrations.AddConstraint(model_name='mpscomplianceholiday',constraint=models.UniqueConstraint(fields=('plant','date'),name='uq_mpscomp_holiday_day')),
        migrations.AddIndex(model_name='mpscomplianceholiday',index=models.Index(fields=['plant','date','is_active'],name='ix_mpscomp_holiday')),
        migrations.CreateModel(name='MPSComplianceOnCallAbsence',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('starts_at',models.DateTimeField()),('ends_at',models.DateTimeField()),('reason',models.CharField(blank=True,max_length=200)),('is_active',models.BooleanField(default=True)),('contact',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='absences',to='integrated_scheduling.mpscomplianceoncallcontact'))],options={'ordering':['-starts_at']}),
        migrations.AddIndex(model_name='mpscomplianceoncallabsence',index=models.Index(fields=['contact','starts_at','ends_at','is_active'],name='ix_mpscomp_absence')),
        migrations.CreateModel(name='MPSComplianceOnCallSubstitution',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('starts_at',models.DateTimeField()),('ends_at',models.DateTimeField()),('levels',models.JSONField(blank=True,default=list,help_text='Níveis cobertos; vazio = todos.')),('reason',models.CharField(blank=True,max_length=200)),('is_active',models.BooleanField(default=True)),('primary_contact',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='substitutions_as_primary',to='integrated_scheduling.mpscomplianceoncallcontact')),('substitute_contact',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='substitutions_as_substitute',to='integrated_scheduling.mpscomplianceoncallcontact'))],options={'ordering':['-starts_at']}),
        migrations.AddIndex(model_name='mpscomplianceoncallsubstitution',index=models.Index(fields=['primary_contact','starts_at','ends_at','is_active'],name='ix_mpscomp_subst')),
        migrations.CreateModel(name='MPSComplianceNotificationDelivery',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('channel',models.CharField(choices=[('EMAIL','E-mail'),('API','API'),('TEAMS','Teams webhook'),('SLACK','Slack webhook')],max_length=12)),('destination',models.CharField(blank=True,max_length=500)),('status',models.CharField(choices=[('SENT','Enviado'),('FAILED','Falhou'),('SKIPPED','Ignorado')],max_length=12)),('attempted_at',models.DateTimeField(default=django.utils.timezone.now)),('response_code',models.IntegerField(blank=True,null=True)),('error',models.TextField(blank=True)),('details',models.JSONField(blank=True,default=dict)),('event',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='deliveries',to='integrated_scheduling.mpscomplianceescalationevent'))],options={'ordering':['-attempted_at','-id']}),
        migrations.AddIndex(model_name='mpscompliancenotificationdelivery',index=models.Index(fields=['channel','status','attempted_at'],name='ix_mpscomp_delivery')),
    ]
