# Generated by Django 5.2.17 on 2026-08-21 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_scheduling', '0040_mps_incident_command_postmortem_099'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpsrevisionoptimizationcandidate',
            options={'ordering': ['pareto_rank', 'rank', 'score', 'id']},
        ),
        migrations.AddField(
            model_name='recoverycommercialimpact',
            name='responsible_area',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='recoverycommercialimpact',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_recovery_commercial_impacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mpscomplianceescalationrule',
            name='channel_endpoints',
            field=models.JSONField(blank=True, default=dict, help_text='Endpoints por canal, ex.: {"SLACK": "https://..."}.'),
        ),
        migrations.AlterField(
            model_name='mpsdecisionauditevent',
            name='event_type',
            field=models.CharField(choices=[('COCKPIT_CREATED', 'Cockpit criado'), ('CANDIDATE_SELECTED', 'Cenário selecionado'), ('SIMULATION_REFERENCED', 'Simulação referenciada'), ('LEGACY_BOOTSTRAP', 'Bootstrap legado'), ('SUBMITTED', 'Enviado para aprovação'), ('AREA_DECISION', 'Decisão de área'), ('RISK_ACCEPTED', 'Risco aceito'), ('AUTHORITY_CREATED', 'Alçada criada'), ('ELECTRONIC_SIGNATURE', 'Assinatura eletrônica'), ('EXECUTIVE_APPROVED', 'Aprovação executiva'), ('EXECUTIVE_REJECTED', 'Rejeição executiva'), ('OFFICIAL_FROZEN', 'Plano oficial congelado'), ('EVIDENCE_EXPORTED', 'Pacote de evidências exportado'), ('ANCHOR_PUBLISHED', 'Âncora externa publicada'), ('ANCHOR_VERIFIED', 'Âncora externa verificada'), ('NOTE', 'Evento informativo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='mpsdecisioncompliancepolicy',
            name='alert_recipients',
            field=models.JSONField(blank=True, default=list, help_text='Lista de e-mails que recebem alertas de compliance.'),
        ),
        migrations.AlterField(
            model_name='mpsdecisioncompliancepolicy',
            name='alert_statuses',
            field=models.JSONField(blank=True, default=list, help_text='Statuses que geram alerta; vazio usa STALE/UNPROTECTED/MISMATCH.'),
        ),
        migrations.AlterField(
            model_name='mpsrevisionsimulationfinancialline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
