# Generated for MRP Django 0.2.1.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [("common", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=240)),
                ("item_type", models.CharField(choices=[("FINISHED", "Produto acabado"), ("ASSEMBLY", "Conjunto"), ("MANUFACTURED", "Fabricado"), ("PURCHASED", "Comprado"), ("RAW", "Matéria-prima"), ("SUBCONTRACTED", "Subcontratado")], max_length=20)),
                ("uom", models.CharField(default="UN", max_length=10)),
                ("status", models.CharField(choices=[("NEW", "Novo"), ("ACTIVE", "Em produção"), ("SUPERSEDED", "Substituído"), ("OBSOLETE", "Obsoleto")], default="ACTIVE", max_length=20)),
                ("low_level_code", models.PositiveIntegerField(db_index=True, default=0)),
                ("standard_cost", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("is_active", models.BooleanField(default=True)),
                ("superseded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supersedes", to="masterdata.item")),
            ],
            options={
                "ordering": ["code"],
                "indexes": [models.Index(fields=["item_type", "is_active"], name="ix_item_type_active")],
                "constraints": [models.CheckConstraint(condition=models.Q(("standard_cost__gte", 0)), name="ck_item_cost_nonneg")],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="WorkCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("capacity_hours_per_day", models.DecimalField(decimal_places=3, default=8, max_digits=10)),
                ("efficiency_percent", models.DecimalField(decimal_places=3, default=100, max_digits=7)),
                ("queue_days", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("preparation_days", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("postoperation_days", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("wait_days", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("is_critical", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_centers", to="common.plant")),
            ],
            options={
                "ordering": ["plant__code", "code"],
                "constraints": [
                    models.UniqueConstraint(fields=("plant", "code"), name="uq_work_center_plant_code"),
                    models.CheckConstraint(condition=models.Q(("capacity_hours_per_day__gt", 0)), name="ck_wc_capacity_pos"),
                    models.CheckConstraint(condition=models.Q(("efficiency_percent__gt", 0)), name="ck_wc_efficiency_pos"),
                    models.CheckConstraint(condition=models.Q(("queue_days__gte", 0)), name="ck_wc_queue_nonneg"),
                    models.CheckConstraint(condition=models.Q(("preparation_days__gte", 0)), name="ck_wc_prep_nonneg"),
                    models.CheckConstraint(condition=models.Q(("postoperation_days__gte", 0)), name="ck_wc_post_nonneg"),
                    models.CheckConstraint(condition=models.Q(("wait_days__gte", 0)), name="ck_wc_wait_nonneg"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=10)),
                ("quantity_per", models.DecimalField(decimal_places=6, max_digits=18)),
                ("scrap_percent", models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ("bom_type", models.CharField(choices=[("ALL", "Todos"), ("ENGINEERING", "Engenharia"), ("MANUFACTURING", "Produção"), ("SPARES", "Reposição")], default="MANUFACTURING", max_length=20)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("engineering_change", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="where_used", to="masterdata.item")),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bom_components", to="masterdata.item")),
            ],
            options={
                "ordering": ["parent__code", "sequence", "component__code"],
                "indexes": [models.Index(fields=["parent", "is_active"], name="ix_bom_parent_active")],
                "constraints": [
                    models.UniqueConstraint(fields=("parent", "component", "sequence"), name="uq_bom_parent_component_sequence"),
                    models.CheckConstraint(condition=models.Q(("quantity_per__gt", 0)), name="ck_bom_quantity_pos"),
                    models.CheckConstraint(condition=models.Q(("scrap_percent__gte", 0)), name="ck_bom_scrap_nonneg"),
                    models.CheckConstraint(condition=~models.Q(parent=models.F("component")), name="ck_bom_parent_diff_comp"),
                    models.CheckConstraint(condition=models.Q(effective_from__isnull=True) | models.Q(effective_to__isnull=True) | models.Q(effective_to__gte=models.F("effective_from")), name="ck_bom_effectivity_dates"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemPlantPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(choices=[("MAKE", "Fabricar"), ("BUY", "Comprar")], max_length=10)),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                ("safety_stock", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("lot_sizing_rule", models.CharField(choices=[("L4L", "Lote por lote"), ("FIXED", "Quantidade fixa"), ("MULTIPLE", "Múltiplo"), ("MINIMUM", "Quantidade mínima")], default="L4L", max_length=12)),
                ("fixed_order_quantity", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("minimum_order_quantity", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("order_multiple", models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ("yield_percent", models.DecimalField(decimal_places=3, default=100, max_digits=7)),
                ("planning_time_fence_days", models.PositiveIntegerField(default=0)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="plant_policies", to="masterdata.item")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="item_policies", to="common.plant")),
            ],
            options={
                "ordering": ["plant__code", "item__code"],
                "constraints": [
                    models.UniqueConstraint(fields=("plant", "item"), name="uq_item_policy_plant_item"),
                    models.CheckConstraint(condition=models.Q(("safety_stock__gte", 0)), name="ck_policy_safety_nonneg"),
                    models.CheckConstraint(condition=models.Q(("fixed_order_quantity__gte", 0)), name="ck_policy_fixed_nonneg"),
                    models.CheckConstraint(condition=models.Q(("minimum_order_quantity__gte", 0)), name="ck_policy_min_nonneg"),
                    models.CheckConstraint(condition=models.Q(("order_multiple__gt", 0)), name="ck_policy_multiple_pos"),
                    models.CheckConstraint(condition=models.Q(("yield_percent__gt", 0)), name="ck_policy_yield_pos"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Routing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(default="STD", max_length=30)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_primary", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="routings", to="masterdata.item")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="routings", to="common.plant")),
            ],
            options={
                "ordering": ["plant__code", "item__code", "code", "version"],
                "constraints": [
                    models.UniqueConstraint(fields=("plant", "item", "code", "version"), name="uq_routing_version"),
                    models.CheckConstraint(condition=models.Q(effective_from__isnull=True) | models.Q(effective_to__isnull=True) | models.Q(effective_to__gte=models.F("effective_from")), name="ck_routing_effect_dates"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemSupplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                ("minimum_order_quantity", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("order_multiple", models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("is_primary", models.BooleanField(default=False)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="suppliers", to="masterdata.item")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="item_suppliers", to="common.plant")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="masterdata.supplier")),
            ],
            options={
                "ordering": ["plant__code", "item__code", "supplier__code"],
                "constraints": [
                    models.UniqueConstraint(fields=("plant", "item", "supplier"), name="uq_item_supplier"),
                    models.CheckConstraint(condition=models.Q(("minimum_order_quantity__gte", 0)), name="ck_itemsupp_min_nonneg"),
                    models.CheckConstraint(condition=models.Q(("order_multiple__gt", 0)), name="ck_itemsupp_multiple_pos"),
                    models.CheckConstraint(condition=models.Q(("unit_price__gte", 0)), name="ck_itemsupp_price_nonneg"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutingOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=200)),
                ("setup_hours", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("run_hours_per_unit", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("teardown_hours", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("move_days", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("yield_percent", models.DecimalField(decimal_places=3, default=100, max_digits=7)),
                ("alternate_work_center", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alternate_operations", to="masterdata.workcenter")),
                ("routing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operations", to="masterdata.routing")),
                ("work_center", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="operations", to="masterdata.workcenter")),
            ],
            options={
                "ordering": ["routing", "sequence"],
                "constraints": [
                    models.UniqueConstraint(fields=("routing", "sequence"), name="uq_routing_operation_sequence"),
                    models.CheckConstraint(condition=models.Q(("setup_hours__gte", 0)), name="ck_routeop_setup_nonneg"),
                    models.CheckConstraint(condition=models.Q(("run_hours_per_unit__gte", 0)), name="ck_routeop_run_nonneg"),
                    models.CheckConstraint(condition=models.Q(("teardown_hours__gte", 0)), name="ck_routeop_teardown_nonneg"),
                    models.CheckConstraint(condition=models.Q(("move_days__gte", 0)), name="ck_routeop_move_nonneg"),
                    models.CheckConstraint(condition=models.Q(("yield_percent__gt", 0)), name="ck_routeop_yield_pos"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkCenterShift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity_hours", models.DecimalField(decimal_places=3, max_digits=10)),
                ("efficiency_percent", models.DecimalField(decimal_places=3, default=100, max_digits=7)),
                ("is_active", models.BooleanField(default=True)),
                ("work_center", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shifts", to="masterdata.workcenter")),
            ],
            options={
                "ordering": ["work_center", "weekday", "start_time"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)), name="ck_shift_weekday_0_6"),
                    models.CheckConstraint(condition=models.Q(("capacity_hours__gt", 0)), name="ck_shift_capacity_pos"),
                    models.CheckConstraint(condition=models.Q(("efficiency_percent__gt", 0)), name="ck_shift_efficiency_pos"),
                    models.UniqueConstraint(fields=("work_center", "weekday", "name"), name="uq_work_center_shift_day_name"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemSubstitute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("priority", models.PositiveIntegerField(default=10)),
                ("substitute_quantity_per_primary", models.DecimalField(decimal_places=6, default=1, help_text="Quantidade do substituto equivalente a uma unidade do item principal.", max_digits=18)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="substitute_options", to="masterdata.item")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="item_substitutes", to="common.plant")),
                ("substitute_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="substitutes_for", to="masterdata.item")),
            ],
            options={
                "ordering": ["plant__code", "item__code", "priority", "substitute_item__code"],
                "constraints": [
                    models.UniqueConstraint(fields=("plant", "item", "substitute_item"), name="uq_item_substitute_plant_pair"),
                    models.CheckConstraint(condition=~models.Q(item=models.F("substitute_item")), name="ck_substitute_items_diff"),
                    models.CheckConstraint(condition=models.Q(("substitute_quantity_per_primary__gt", 0)), name="ck_substitute_ratio_pos"),
                    models.CheckConstraint(condition=models.Q(effective_from__isnull=True) | models.Q(effective_to__isnull=True) | models.Q(effective_to__gte=models.F("effective_from")), name="ck_substitute_effect_dates"),
                ],
            },
        ),
    ]
