from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[("common","0001_initial"),("masterdata","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name="CostVersion",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=40)),("description",models.CharField(blank=True,max_length=200)),("effective_from",models.DateField()),("effective_to",models.DateField(blank=True,null=True)),("status",models.CharField(choices=[("DRAFT","Rascunho"),("CALCULATED","Calculada"),("APPROVED","Aprovada"),("ACTIVE","Ativa"),("CLOSED","Encerrada")],db_index=True,default="DRAFT",max_length=16)),("calculated_at",models.DateTimeField(blank=True,null=True)),("approved_at",models.DateTimeField(blank=True,null=True)),("approved_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="approved_cost_versions",to=settings.AUTH_USER_MODEL)),("plant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="cost_versions",to="common.plant"))],options={"ordering":["-effective_from","code"]}),
      migrations.AddConstraint(model_name="costversion",constraint=models.UniqueConstraint(fields=("plant","code"),name="uq_cost_version_plant_code")),
      migrations.CreateModel(name="WorkCenterRate",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("setup_rate",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("labor_rate",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("machine_rate",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("overhead_rate",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("cost_version",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="work_center_rates",to="costing.costversion")),("work_center",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="cost_rates",to="masterdata.workcenter"))]),
      migrations.AddConstraint(model_name="workcenterrate",constraint=models.UniqueConstraint(fields=("cost_version","work_center"),name="uq_cost_wc_rate")),
      migrations.CreateModel(name="ItemCost",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("material_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("setup_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("labor_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("machine_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("overhead_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("subcontract_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("total_cost",models.DecimalField(db_index=True,decimal_places=4,default=0,max_digits=18)),("level",models.PositiveIntegerField(default=0)),("calculation_details",models.JSONField(blank=True,default=dict)),("cost_version",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="item_costs",to="costing.costversion")),("item",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="cost_records",to="masterdata.item"))],options={"ordering":["item__low_level_code","item__code"]}),
      migrations.AddConstraint(model_name="itemcost",constraint=models.UniqueConstraint(fields=("cost_version","item"),name="uq_item_cost_version")),
      migrations.CreateModel(name="CostRollupRun",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("status",models.CharField(choices=[("PENDING","Pendente"),("RUNNING","Executando"),("COMPLETED","Concluída"),("FAILED","Falhou")],default="PENDING",max_length=16)),("started_at",models.DateTimeField(blank=True,null=True)),("finished_at",models.DateTimeField(blank=True,null=True)),("items_calculated",models.PositiveIntegerField(default=0)),("error_message",models.TextField(blank=True)),("cost_version",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="rollup_runs",to="costing.costversion"))])
    ]
