from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [("costing", "0001_initial"), ("production", "0001_initial"), ("purchasing", "0001_initial")]
    operations = [
        migrations.CreateModel(name="WorkOrderCost", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("cost_type",models.CharField(choices=[("PLANNED","Planejado"),("ACTUAL","Real")],max_length=12)),("quantity_basis",models.DecimalField(decimal_places=4,max_digits=18)),("material_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("setup_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("labor_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("machine_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("overhead_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("subcontract_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("scrap_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("rework_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("total_cost",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("unit_cost",models.DecimalField(decimal_places=6,default=0,max_digits=18)),("calculated_at",models.DateTimeField()),("calculation_details",models.JSONField(blank=True,default=dict)),("cost_version",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="work_order_costs",to="costing.costversion")),("work_order",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="cost_summaries",to="production.workorder"))], options={"constraints":[models.UniqueConstraint(fields=("work_order","cost_type"),name="uq_wo_cost_type")]}),
        migrations.CreateModel(name="WorkOrderCostLine", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("category",models.CharField(max_length=20)),("reference",models.CharField(blank=True,max_length=80)),("quantity",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("hours",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("rate",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("amount",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("details",models.JSONField(blank=True,default=dict)),("item",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="work_order_cost_lines",to="masterdata.item")),("work_center",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="work_order_cost_lines",to="masterdata.workcenter")),("work_order_cost",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="lines",to="costing.workordercost"))]),
        migrations.CreateModel(name="CostVariance", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("variance_type",models.CharField(max_length=30)),("planned_amount",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("actual_amount",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("variance_amount",models.DecimalField(decimal_places=4,default=0,max_digits=18)),("favorable",models.BooleanField(default=False)),("details",models.JSONField(blank=True,default=dict)),("work_order",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="cost_variances",to="production.workorder"))], options={"constraints":[models.UniqueConstraint(fields=("work_order","variance_type"),name="uq_wo_variance_type")]}),
        migrations.CreateModel(name="PurchasePriceVariance", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("standard_unit_cost",models.DecimalField(decimal_places=4,max_digits=18)),("actual_unit_price",models.DecimalField(decimal_places=4,max_digits=18)),("quantity",models.DecimalField(decimal_places=4,max_digits=18)),("variance_amount",models.DecimalField(decimal_places=4,max_digits=18)),("favorable",models.BooleanField(default=False)),("cost_version",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="purchase_price_variances",to="costing.costversion")),("goods_receipt",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="price_variance",to="purchasing.goodsreceipt"))], options={"ordering":["-created_at"]}),
        migrations.AddIndex(model_name="workordercost", index=models.Index(fields=["cost_version","cost_type"], name="ix_wocost_version_type")),
    ]
