from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies=[("costing","0003_inventory_wip_period"),("inventory","0001_initial")]
    operations=[
        migrations.CreateModel(name="MovingAverageCostBalance", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),
            ("quantity",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("inventory_value",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("average_unit_cost",models.DecimalField(decimal_places=6,default=0,max_digits=22)),
            ("item",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="moving_average_costs",to="masterdata.item")),("last_transaction",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="moving_average_balances",to="inventory.inventorytransaction")),("plant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="moving_average_costs",to="common.plant"))]),
        migrations.CreateModel(name="InventoryCostMovement", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("movement_type",models.CharField(choices=[("RECEIPT","Entrada"),("ISSUE","Saída"),("ADJUSTMENT","Ajuste"),("REVALUATION","Reavaliação"),("TRANSFER","Transferência")],max_length=20)),("quantity",models.DecimalField(decimal_places=4,max_digits=22)),("unit_cost",models.DecimalField(decimal_places=6,default=0,max_digits=22)),("value",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("quantity_after",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("value_after",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("average_cost_after",models.DecimalField(decimal_places=6,default=0,max_digits=22)),("reference_type",models.CharField(blank=True,max_length=40)),("reference_id",models.CharField(blank=True,max_length=64)),("posted_at",models.DateTimeField(db_index=True,default=django.utils.timezone.now)),("details",models.JSONField(blank=True,default=dict)),("item",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inventory_cost_movements",to="masterdata.item")),("plant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inventory_cost_movements",to="common.plant")),("transaction",models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="cost_movement",to="inventory.inventorytransaction"))], options={"ordering":["posted_at","id"]}),
        migrations.CreateModel(name="CostLedgerEntry", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("entry_type",models.CharField(choices=[("INVENTORY","Estoque"),("WIP","Produção em processo"),("VARIANCE","Variação"),("ADJUSTMENT","Ajuste"),("PERIOD_CLOSE","Fechamento")],db_index=True,max_length=20)),("posting_date",models.DateField(db_index=True)),("account_code",models.CharField(max_length=40)),("debit",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("credit",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("reference_type",models.CharField(blank=True,max_length=40)),("reference_id",models.CharField(blank=True,max_length=64)),("description",models.CharField(blank=True,max_length=240)),("idempotency_key",models.CharField(max_length=180,unique=True)),("details",models.JSONField(blank=True,default=dict)),("period",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="ledger_entries",to="costing.accountingperiod")),("plant",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="cost_ledger_entries",to="common.plant"))], options={"ordering":["posting_date","id"]}),
        migrations.CreateModel(name="PeriodVariancePosting", fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("variance_type",models.CharField(choices=[("MATERIAL_PRICE","Preço de material"),("MATERIAL_USAGE","Consumo de material"),("LABOR_RATE","Taxa de mão de obra"),("LABOR_EFFICIENCY","Eficiência de mão de obra"),("MACHINE_EFFICIENCY","Eficiência de máquina"),("SETUP","Setup"),("OVERHEAD","Custos indiretos"),("SCRAP","Refugo"),("TOTAL","Total")],max_length=30)),("amount",models.DecimalField(decimal_places=4,default=0,max_digits=22)),("favorable",models.BooleanField(default=False)),("posted_at",models.DateTimeField(blank=True,null=True)),("ledger_credit",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="variance_credits",to="costing.costledgerentry")),("ledger_debit",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="variance_debits",to="costing.costledgerentry")),("period",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="variance_postings",to="costing.accountingperiod"))], options={"ordering":["variance_type"]}),
        migrations.AddConstraint(model_name="movingaveragecostbalance",constraint=models.UniqueConstraint(fields=("plant","item"),name="uq_mavg_plant_item")),
        migrations.AddConstraint(model_name="movingaveragecostbalance",constraint=models.CheckConstraint(condition=models.Q(("quantity__gte",0)),name="ck_mavg_qty_nonneg")),
        migrations.AddConstraint(model_name="movingaveragecostbalance",constraint=models.CheckConstraint(condition=models.Q(("inventory_value__gte",0)),name="ck_mavg_value_nonneg")),
        migrations.AddIndex(model_name="movingaveragecostbalance",index=models.Index(fields=["plant","item"],name="ix_mavg_plant_item")),
        migrations.AddIndex(model_name="inventorycostmovement",index=models.Index(fields=["plant","item","posted_at"],name="ix_costmov_item_time")),
        migrations.AddConstraint(model_name="costledgerentry",constraint=models.CheckConstraint(condition=models.Q(("debit__gte",0)),name="ck_costledger_debit_nonneg")),
        migrations.AddConstraint(model_name="costledgerentry",constraint=models.CheckConstraint(condition=models.Q(("credit__gte",0)),name="ck_costledger_credit_nonneg")),
        migrations.AddConstraint(model_name="costledgerentry",constraint=models.CheckConstraint(condition=models.Q(models.Q(("credit",0),("debit__gt",0)),models.Q(("credit__gt",0),("debit",0)),_connector="OR"),name="ck_costledger_one_side")),
        migrations.AddIndex(model_name="costledgerentry",index=models.Index(fields=["plant","posting_date","entry_type"],name="ix_costledger_plant_date")),
        migrations.AddConstraint(model_name="periodvarianceposting",constraint=models.UniqueConstraint(fields=("period","variance_type"),name="uq_period_variance_type")),
    ]
