from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("costing", "0004_moving_average_cost_ledger"),
        ("traceability", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryRevaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(choices=[("STANDARD", "Custo padrão"), ("MOVING_AVERAGE", "Custo médio móvel"), ("MANUAL", "Manual")], default="MANUAL", max_length=20)),
                ("quantity", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("old_unit_cost", models.DecimalField(decimal_places=6, default=0, max_digits=22)),
                ("new_unit_cost", models.DecimalField(decimal_places=6, default=0, max_digits=22)),
                ("old_value", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("new_value", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("variance_value", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("reason", models.CharField(max_length=240)),
                ("posted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("idempotency_key", models.CharField(max_length=180, unique=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_revaluations", to="masterdata.item")),
                ("ledger_credit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="revaluation_credits", to="costing.costledgerentry")),
                ("ledger_debit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="revaluation_debits", to="costing.costledgerentry")),
                ("period", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="inventory_revaluations", to="costing.accountingperiod")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_revaluations", to="common.plant")),
                ("posted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="posted_inventory_revaluations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-posted_at", "item__code"]},
        ),
        migrations.CreateModel(
            name="FinancialInventoryAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_delta", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("value_delta", models.DecimalField(decimal_places=4, max_digits=22)),
                ("reason_code", models.CharField(default="OTHER", max_length=40)),
                ("reason", models.CharField(max_length=240)),
                ("status", models.CharField(choices=[("DRAFT", "Rascunho"), ("POSTED", "Contabilizado"), ("REVERSED", "Estornado")], db_index=True, default="DRAFT", max_length=12)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=180, unique=True)),
                ("inventory_transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_adjustments", to="inventory.inventorytransaction")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="financial_inventory_adjustments", to="masterdata.item")),
                ("ledger_credit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_credits", to="costing.costledgerentry")),
                ("ledger_debit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="adjustment_debits", to="costing.costledgerentry")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_adjustments", to="inventory.location")),
                ("period", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_inventory_adjustments", to="costing.accountingperiod")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="financial_inventory_adjustments", to="common.plant")),
                ("posted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="posted_financial_inventory_adjustments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="LotActualCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_basis", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("purchase_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("material_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("conversion_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("quality_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("scrap_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("total_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("unit_cost", models.DecimalField(decimal_places=6, default=0, max_digits=22)),
                ("calculated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("cost_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="lot_actual_costs", to="costing.costversion")),
                ("lot", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="actual_cost", to="traceability.inventorylot")),
            ],
            options={"ordering": ["lot__item__code", "lot__lot_number"]},
        ),
        migrations.CreateModel(
            name="SerialActualCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("component_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("conversion_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("total_cost", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("calculated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("serial", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="actual_cost", to="traceability.serialnumber")),
            ],
            options={"ordering": ["serial__item__code", "serial__serial_number"]},
        ),
        migrations.CreateModel(
            name="InventoryReconciliationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("as_of", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("RUNNING", "Executando"), ("COMPLETED", "Concluída"), ("RECONCILED", "Conciliada")], default="RUNNING", max_length=16)),
                ("physical_quantity", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("financial_quantity", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("physical_value", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("financial_value", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("quantity_variance", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("value_variance", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_reconciliation_runs", to=settings.AUTH_USER_MODEL)),
                ("period", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reconciliation_runs", to="costing.accountingperiod")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_reconciliation_runs", to="common.plant")),
            ],
            options={"ordering": ["-as_of"]},
        ),
        migrations.CreateModel(
            name="InventoryReconciliationLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("physical_quantity", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("financial_quantity", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("unit_cost", models.DecimalField(decimal_places=6, default=0, max_digits=22)),
                ("physical_value", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("financial_value", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("quantity_variance", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("value_variance", models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ("reconciled", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_reconciliation_lines", to="masterdata.item")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="costing.inventoryreconciliationrun")),
            ],
            options={"ordering": ["item__code"]},
        ),
        migrations.AddConstraint(model_name="financialinventoryadjustment", constraint=models.CheckConstraint(condition=~models.Q(value_delta=0), name="ck_finadj_value_nonzero")),
        migrations.AddConstraint(model_name="inventoryreconciliationline", constraint=models.UniqueConstraint(fields=("run", "item"), name="uq_reconciliation_run_item")),
        migrations.AddIndex(model_name="inventoryrevaluation", index=models.Index(fields=["plant", "item", "posted_at"], name="ix_reval_plant_item_time")),
        migrations.AddIndex(model_name="financialinventoryadjustment", index=models.Index(fields=["plant", "status", "created_at"], name="ix_finadj_plant_status")),
    ]
