# Generated by Django 5.2.17 on 2026-08-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_period_close_reopen_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workordercostline',
            options={'ordering': ['category', 'id']},
        ),
        migrations.AlterField(
            model_name='costrolluprun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='costvariance',
            name='variance_type',
            field=models.CharField(choices=[('MATERIAL_PRICE', 'Preço de material'), ('MATERIAL_USAGE', 'Consumo de material'), ('LABOR_RATE', 'Taxa de mão de obra'), ('LABOR_EFFICIENCY', 'Eficiência de mão de obra'), ('MACHINE_EFFICIENCY', 'Eficiência de máquina'), ('SETUP', 'Setup'), ('OVERHEAD', 'Custos indiretos'), ('SCRAP', 'Refugo'), ('TOTAL', 'Total')], max_length=30),
        ),
        migrations.AlterField(
            model_name='costversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemcost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workcenterrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workordercostline',
            name='category',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('SETUP', 'Setup'), ('LABOR', 'Mão de obra'), ('MACHINE', 'Máquina'), ('OVERHEAD', 'Indireto'), ('SUBCONTRACT', 'Subcontratação'), ('SCRAP', 'Refugo'), ('REWORK', 'Retrabalho')], max_length=20),
        ),
    ]
