# Generated by Django 5.2.17 on 2026-08-21 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0003_supplier_installments_086'),
        ('traceability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotbalance',
            options={'ordering': ['lot__item__code', 'lot__lot_number', 'location__code']},
        ),
        migrations.AlterModelOptions(
            name='lotreservation',
            options={'ordering': ['required_date', 'lot__item__code', 'lot__lot_number']},
        ),
        migrations.AlterModelOptions(
            name='lottransaction',
            options={'ordering': ['-posted_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='serialcomponent',
            options={'ordering': ['parent_serial__serial_number', 'installed_at']},
        ),
        migrations.AlterModelOptions(
            name='serialnumber',
            options={'ordering': ['item__code', 'serial_number']},
        ),
        migrations.AlterModelOptions(
            name='serialtransaction',
            options={'ordering': ['-posted_at', '-id']},
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['plant', 'item', 'status'], name='ix_lot_plant_item_status'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['expiration_date', 'status'], name='ix_lot_exp_status'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['source_type', 'source_id'], name='ix_lot_source'),
        ),
        migrations.AddIndex(
            model_name='lotbalance',
            index=models.Index(fields=['location', 'lot'], name='ix_lotbal_location_lot'),
        ),
        migrations.AddIndex(
            model_name='lotreservation',
            index=models.Index(fields=['demand_type', 'demand_id', 'status'], name='ix_lotres_demand'),
        ),
        migrations.AddIndex(
            model_name='lotreservation',
            index=models.Index(fields=['lot', 'status', 'required_date'], name='ix_lotres_lot_date'),
        ),
        migrations.AddIndex(
            model_name='lottransaction',
            index=models.Index(fields=['lot', 'posted_at'], name='ix_lottx_lot_posted'),
        ),
        migrations.AddIndex(
            model_name='lottransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='ix_lottx_reference'),
        ),
        migrations.AddIndex(
            model_name='serialcomponent',
            index=models.Index(fields=['parent_serial', 'removed_at'], name='ix_serialcomp_parent_active'),
        ),
        migrations.AddIndex(
            model_name='serialcomponent',
            index=models.Index(fields=['component_serial', 'removed_at'], name='ix_serialcomp_component_active'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['plant', 'item', 'status'], name='ix_serial_plant_item_status'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['source_type', 'source_id'], name='ix_serial_source'),
        ),
        migrations.AddIndex(
            model_name='serialtransaction',
            index=models.Index(fields=['serial', 'posted_at'], name='ix_serialtx_serial_posted'),
        ),
        migrations.AddIndex(
            model_name='serialtransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='ix_serialtx_reference'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('expiration_date__isnull', True), ('manufacture_date__isnull', True), ('expiration_date__gte', models.F('manufacture_date')), _connector='OR'), name='ck_lot_exp_after_mfg'),
        ),
        migrations.AddConstraint(
            model_name='lotbalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='ck_lotbal_onhand_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='lotbalance',
            constraint=models.CheckConstraint(condition=models.Q(('allocated__gte', 0)), name='ck_lotbal_alloc_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='lotbalance',
            constraint=models.CheckConstraint(condition=models.Q(('allocated__lte', models.F('on_hand'))), name='ck_lotbal_alloc_lte_onhand'),
        ),
        migrations.AddConstraint(
            model_name='lotreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_lotres_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='lotreservation',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_quantity__gte', 0)), name='ck_lotres_cons_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='lotreservation',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_quantity__lte', models.F('quantity'))), name='ck_lotres_cons_lte_qty'),
        ),
        migrations.AddConstraint(
            model_name='lottransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_lottx_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='serialcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_serialcomp_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='serialcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('parent_serial', models.F('component_serial')), _negated=True), name='ck_serialcomp_not_self'),
        ),
    ]
