# Generated manually for MRP 0.5.8.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("maintenance", "0001_initial")]
    operations = [
        migrations.CreateModel(name="TechnicianSkill", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=40, unique=True)),("name",models.CharField(max_length=120)),("description",models.TextField(blank=True)),("is_active",models.BooleanField(default=True))], options={"ordering":["code"]}),
        migrations.CreateModel(name="TechnicianProfile", fields=[("id",models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("employee_code",models.CharField(max_length=40)),("daily_capacity_hours",models.DecimalField(decimal_places=2, default=8, max_digits=6)),("is_active",models.BooleanField(default=True)),("plant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_technicians", to="common.plant")),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_technician", to=settings.AUTH_USER_MODEL))], options={"ordering":["plant__code","employee_code"],"constraints":[models.UniqueConstraint(fields=("plant","employee_code"), name="uq_maint_tech_plant_code"),models.CheckConstraint(condition=models.Q(("daily_capacity_hours__gte",0)), name="ck_maint_tech_capacity_nonneg")]}),
        migrations.CreateModel(name="MaintenanceSLA", fields=[("id",models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("priority",models.CharField(choices=[("LOW","Baixa"),("NORMAL","Normal"),("HIGH","Alta"),("EMERGENCY","Emergência")], max_length=20)),("response_hours",models.DecimalField(decimal_places=2, default=0, max_digits=8)),("resolution_hours",models.DecimalField(decimal_places=2, default=0, max_digits=8)),("is_active",models.BooleanField(default=True)),("plant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_slas", to="common.plant"))], options={"constraints":[models.UniqueConstraint(fields=("plant","priority"), name="uq_maint_sla_plant_priority"),models.CheckConstraint(condition=models.Q(("response_hours__gte",0)), name="ck_maint_sla_response_nonneg"),models.CheckConstraint(condition=models.Q(("resolution_hours__gte",0)), name="ck_maint_sla_resolution_nonneg")]}),
        migrations.CreateModel(name="ConditionReading", fields=[("id",models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("metric",models.CharField(choices=[("VIBRATION","Vibração"),("TEMPERATURE","Temperatura"),("PRESSURE","Pressão"),("CURRENT","Corrente"),("CUSTOM","Outro")], max_length=20)),("metric_name",models.CharField(blank=True, max_length=80)),("value",models.DecimalField(decimal_places=4, max_digits=18)),("unit",models.CharField(blank=True, max_length=20)),("reading_at",models.DateTimeField(default=django.utils.timezone.now)),("source",models.CharField(default="MANUAL", max_length=40)),("asset",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="condition_readings", to="maintenance.maintenanceasset")),("recorded_by",models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_condition_readings", to=settings.AUTH_USER_MODEL))], options={"ordering":["-reading_at","-id"],"indexes":[models.Index(fields=["asset","metric","reading_at"], name="ix_cond_asset_metric")]}),
        migrations.CreateModel(name="ConditionRule", fields=[("id",models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=50)),("metric",models.CharField(choices=[("VIBRATION","Vibração"),("TEMPERATURE","Temperatura"),("PRESSURE","Pressão"),("CURRENT","Corrente"),("CUSTOM","Outro")], max_length=20)),("metric_name",models.CharField(blank=True, max_length=80)),("comparator",models.CharField(choices=[("GT",">"),("GTE",">="),("LT","<"),("LTE","<=")], default="GTE", max_length=4)),("threshold",models.DecimalField(decimal_places=4, max_digits=18)),("priority",models.CharField(choices=[("LOW","Baixa"),("NORMAL","Normal"),("HIGH","Alta"),("EMERGENCY","Emergência")], default="HIGH", max_length=20)),("title",models.CharField(max_length=180)),("is_active",models.BooleanField(default=True)),("asset",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="condition_rules", to="maintenance.maintenanceasset"))], options={"constraints":[models.UniqueConstraint(fields=("asset","code"), name="uq_maint_condition_rule")]}),
        migrations.CreateModel(name="TechnicianSkillAssignment", fields=[("id",models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("proficiency",models.PositiveSmallIntegerField(default=1)),("valid_until",models.DateField(blank=True, null=True)),("skill",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="technician_assignments", to="maintenance.technicianskill")),("technician",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_assignments", to="maintenance.technicianprofile"))], options={"constraints":[models.UniqueConstraint(fields=("technician","skill"), name="uq_maint_tech_skill"),models.CheckConstraint(condition=models.Q(("proficiency__gte",1),("proficiency__lte",5)), name="ck_maint_skill_prof_1_5")]}),
        migrations.CreateModel(name="WorkOrderAssignment", fields=[("id",models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("planned_hours",models.DecimalField(decimal_places=2, default=0, max_digits=8)),("actual_hours",models.DecimalField(decimal_places=2, default=0, max_digits=8)),("is_lead",models.BooleanField(default=False)),("technician",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="work_order_assignments", to="maintenance.technicianprofile")),("work_order",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="technician_assignments", to="maintenance.maintenanceworkorder"))], options={"constraints":[models.UniqueConstraint(fields=("work_order","technician"), name="uq_maint_wo_technician"),models.CheckConstraint(condition=models.Q(("planned_hours__gte",0)), name="ck_maint_assign_plan_nonneg"),models.CheckConstraint(condition=models.Q(("actual_hours__gte",0)), name="ck_maint_assign_actual_nonneg")]}),
    ]
