# Generated for MRP Django 0.2.1.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("common", "0001_initial"), ("masterdata", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PlanningRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("horizon_start", models.DateField()),
                ("horizon_end", models.DateField()),
                ("status", models.CharField(choices=[("DRAFT", "Rascunho"), ("RUNNING", "Executando"), ("COMPLETED", "Concluída"), ("FAILED", "Falhou")], default="DRAFT", max_length=15)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="planning_runs", to="common.plant")),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [models.CheckConstraint(condition=models.Q(horizon_end__gte=models.F("horizon_start")), name="ck_planrun_horizon")],
            },
        ),
        migrations.CreateModel(
            name="CapacityScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("scenario_type", models.CharField(choices=[("CRP", "Planejamento de capacidade"), ("CTP", "Capable to Promise"), ("WHAT_IF", "Simulação what-if")], max_length=16)),
                ("quantity", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("requested_release_date", models.DateField(blank=True, null=True)),
                ("requested_due_date", models.DateField(blank=True, null=True)),
                ("promised_date", models.DateField(blank=True, null=True)),
                ("feasible", models.BooleanField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("DRAFT", "Rascunho"), ("RUNNING", "Executando"), ("COMPLETED", "Concluído"), ("FAILED", "Falhou")], default="DRAFT", max_length=16)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="capacity_scenarios", to="masterdata.item")),
                ("planning_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="capacity_scenarios", to="planning.planningrun")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capacity_scenarios", to="common.plant")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["plant", "scenario_type", "status"], name="ix_capscenario_plant_type")],
                "constraints": [models.CheckConstraint(condition=models.Q(("quantity__gte", 0)), name="ck_capscenario_qty_nonneg")],
            },
        ),
        migrations.CreateModel(
            name="PlannedOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_type", models.CharField(choices=[("MAKE", "Ordem de produção"), ("PURCHASE", "Ordem de compra")], max_length=12)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("release_date", models.DateField()),
                ("due_date", models.DateField()),
                ("status", models.CharField(choices=[("PLANNED", "Planejada"), ("FIRM", "Firme"), ("CONVERTED", "Convertida"), ("CANCELLED", "Cancelada")], default="PLANNED", max_length=15)),
                ("source", models.CharField(default="MRP", max_length=80)),
                ("converted_document_type", models.CharField(blank=True, max_length=30)),
                ("converted_document_id", models.CharField(blank=True, max_length=64)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="planned_orders", to="masterdata.item")),
                ("planning_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planned_orders", to="planning.planningrun")),
            ],
            options={
                "ordering": ["release_date", "item__code"],
                "indexes": [models.Index(fields=["planning_run", "order_type", "release_date"], name="ix_plorder_run_type_date")],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="ck_plorder_qty_pos"),
                    models.CheckConstraint(condition=models.Q(due_date__gte=models.F("release_date")), name="ck_plorder_dates"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanningBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bucket_date", models.DateField()),
                ("gross_requirements", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("scheduled_receipts", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("projected_available", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("net_requirements", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("planned_order_receipts", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("planned_order_releases", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planning_buckets", to="masterdata.item")),
                ("planning_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="buckets", to="planning.planningrun")),
            ],
            options={
                "ordering": ["item__low_level_code", "item__code", "bucket_date"],
                "constraints": [models.UniqueConstraint(fields=("planning_run", "item", "bucket_date"), name="uq_planning_bucket")],
            },
        ),
        migrations.CreateModel(
            name="PeggingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requirement_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("component_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="component_pegging_records", to="masterdata.item")),
                ("parent_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parent_pegging_records", to="masterdata.item")),
                ("parent_planned_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="component_pegging", to="planning.plannedorder")),
                ("planning_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pegging_records", to="planning.planningrun")),
                ("top_level_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="top_level_pegging", to="masterdata.item")),
            ],
            options={
                "ordering": ["component_item__code", "requirement_date"],
                "indexes": [
                    models.Index(fields=["planning_run", "component_item", "requirement_date"], name="ix_pegging_component_date"),
                    models.Index(fields=["planning_run", "top_level_item"], name="ix_pegging_top_item"),
                ],
                "constraints": [models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="ck_pegging_qty_pos")],
            },
        ),
        migrations.CreateModel(
            name="PlanningMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_type", models.CharField(choices=[("RELEASE", "Liberar ordem"), ("PAST_DUE", "Data vencida"), ("SHORTAGE", "Falta"), ("RESCHEDULE_IN", "Antecipar"), ("RESCHEDULE_OUT", "Postergar"), ("DATA_ERROR", "Erro de cadastro")], max_length=20)),
                ("severity", models.CharField(choices=[("INFO", "Informação"), ("WARNING", "Atenção"), ("ERROR", "Erro")], default="INFO", max_length=10)),
                ("action_date", models.DateField(blank=True, null=True)),
                ("suggested_date", models.DateField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, max_length=40)),
                ("reference_id", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField()),
                ("item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="masterdata.item")),
                ("planned_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="planning.plannedorder")),
                ("planning_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="planning.planningrun")),
            ],
            options={
                "ordering": ["severity", "action_date", "item__code"],
                "indexes": [models.Index(fields=["planning_run", "severity", "action_date"], name="ix_planmsg_run_sev_date")],
            },
        ),
        migrations.CreateModel(
            name="CapacityAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(max_length=30)),
                ("source_id", models.CharField(max_length=64)),
                ("operation_sequence", models.PositiveIntegerField(default=0)),
                ("load_date", models.DateField()),
                ("week_start", models.DateField(db_index=True)),
                ("required_hours", models.DecimalField(decimal_places=4, max_digits=18)),
                ("available_hours", models.DecimalField(decimal_places=4, max_digits=18)),
                ("allocated_hours", models.DecimalField(decimal_places=4, max_digits=18)),
                ("overload_hours", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("is_existing_load", models.BooleanField(default=False)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capacity_allocations", to="masterdata.item")),
                ("scenario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="planning.capacityscenario")),
                ("work_center", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capacity_allocations", to="masterdata.workcenter")),
            ],
            options={
                "ordering": ["load_date", "work_center__code", "source_type", "source_id", "operation_sequence"],
                "indexes": [
                    models.Index(fields=["scenario", "work_center", "load_date"], name="ix_capalloc_center_date"),
                    models.Index(fields=["scenario", "week_start"], name="ix_capalloc_week"),
                ],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("required_hours__gte", 0)), name="ck_capalloc_req_nonneg"),
                    models.CheckConstraint(condition=models.Q(("available_hours__gte", 0)), name="ck_capalloc_avail_nonneg"),
                    models.CheckConstraint(condition=models.Q(("allocated_hours__gte", 0)), name="ck_capalloc_alloc_nonneg"),
                    models.CheckConstraint(condition=models.Q(("overload_hours__gte", 0)), name="ck_capalloc_over_nonneg"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanningChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("change_type", models.CharField(choices=[("DEMAND", "Demanda"), ("STOCK", "Estoque"), ("BOM", "Estrutura"), ("POLICY", "Política"), ("SUPPLY", "Suprimento"), ("ROUTING", "Roteiro/capacidade")], max_length=16)),
                ("source_type", models.CharField(max_length=50)),
                ("source_id", models.CharField(max_length=80)),
                ("idempotency_key", models.CharField(max_length=180, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("PENDING", "Pendente"), ("PROCESSED", "Processada"), ("CANCELLED", "Cancelada")], default="PENDING", max_length=16)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="planning_changes", to="masterdata.item")),
                ("planning_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_changes", to="planning.planningrun")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planning_changes", to="common.plant")),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [models.Index(fields=["plant", "status", "created_at"], name="ix_plchange_status_time")],
            },
        ),
    ]
